### ISSUE TITLE
Workflow steps are displayed even if not workflow

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#189]
Workflow steps are displayed even if not workflow (with the default step image processing), but there are not accessible, and quick edit remove will not remove them.
Expected behavior: if not a wf, wf step not displayed.

**Comment by czhci** [comment]
not only show as "image processing", can also be "operation", as in https://biii.eu/vast-lite.

**Comment by miura** [comment]
Maybe this is fixed with Drupal9.5?

http://test.biii.eu/

pls check.

**Comment by PerrineGilloteaux** [comment]
Drupal 9 does not fixed it, I've just tested from test.biii.eu. It comes from the configuration of the view, working on it (will  point you here the associated commit)

**Comment by PerrineGilloteaux** [comment]
fixed and tested. 395b8263050c800fe452df93b7db8dea892b82a4 
NB: one the fix is deployed, the correction will not apply retroactively: I am testing actions to trigger an edit for all Software entry on my local version. If not working, all entries will have to be parse to edit with no revisions, just to trigger the change. Will let you know.

**Comment by PerrineGilloteaux** [comment]
Ok, so after the fix a simple edit save will reset the display (for now if you want to remove wf step you have to set the sf step to wf, erase the field, then set back the wf type to what it was (component or collection).
I've tested some bulk operations with the hope they will have the same effect but no. So my suggestion is 
1) deploy the fix above (that make in any case the correction easier, and prevent it to happen again) 
 2) from the content view, click edit then save all sf entries with a pb.
